services:
  dev_api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: dev_server
    ports:
      - "8080:8080"
    environment:
      NODE_ENV: development
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/mydb?schema=public
      JWT_SECRET: your-jwt-secret-change-in-production
      FRONTEND_URL: http://localhost:5173
      PORT: 8080
    depends_on: [postgres]
    command: npm run dev

  postgres:
    image: postgres:16-alpine
    container_name: dev_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydb
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
