services:
  dev_api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: dev_server
    ports:
      - "8080:8080"
    environment:
      NODE_ENV: ${NODE_ENV:-development}
      DATABASE_URL: ${DATABASE_URL:-postgresql://postgres:postgres@postgres:5432/mydb?schema=public}
      JWT_SECRET: ${JWT_SECRET:-jwt-secret-change-in-production}
      FRONTEND_URL: ${FRONTEND_URL:-http://localhost:5173}
      PORT: ${PORT:-8080}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_REGION: ${AWS_REGION:-eu-north-1}
      AWS_S3_BUCKET_NAME: ${AWS_S3_BUCKET_NAME}
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on: [postgres]
    command: npm run dev

  postgres:
    image: postgres:16-alpine
    container_name: dev_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydb
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
