import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card'
import { Hash } from 'lucide-react'
import { useI18n } from '@/contexts/I18nContext'

export const CustomIdPreview = ({ previewId, hasCustomId }) => {
  const { t } = useI18n()

  if (!hasCustomId) return null

  return (
    <Card className="border-2 border-primary">
      <CardHeader>
        <CardTitle className="flex items-center">
          <Hash className="mr-2 h-5 w-5" />
          {t('customId')}
        </CardTitle>
        <CardDescription>
          {t('customIdAutoGenerated')}
        </CardDescription>
      </CardHeader>
      <CardContent>
        {previewId && (
          <div className="p-3 bg-muted rounded-lg">
            <p className="text-xs text-muted-foreground mb-1">{t('exampleIdFormat')}</p>
            <p className="font-mono text-sm">{previewId}</p>
            <p className="text-xs text-muted-foreground mt-2">
              {t('actualIdGeneratedOnServer')}
            </p>
          </div>
        )}
      </CardContent>
    </Card>
  )
}

