import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card'
import { Hash, Sparkles } from 'lucide-react'
import { useI18n } from '@/contexts/I18nContext'

export const CustomIdPreview = ({ 
  preview, 
  hasCustomId = true,
  variant = 'default',
  title,
  description 
}) => {
  const { t } = useI18n()

  if (!hasCustomId) return null

  const defaultTitle = variant === 'live' ? t('livePreview') : t('customId')
  const defaultDescription = variant === 'live' 
    ? t('exampleGeneratedId') 
    : t('customIdAutoGenerated')
  
  const Icon = variant === 'live' ? Sparkles : Hash

  return (
    <Card className="border-2 border-primary">
      <CardHeader>
        <CardTitle className="flex items-center">
          <Icon className="mr-2 h-5 w-5" />
          {title || defaultTitle}
        </CardTitle>
        <CardDescription>
          {description || defaultDescription}
        </CardDescription>
      </CardHeader>
      <CardContent>
        {preview ? (
          <div className="p-3 bg-muted rounded-lg">
            <p className="text-xs text-muted-foreground mb-1">{t('exampleIdFormat')}</p>
            <p className="font-mono text-lg break-all">{preview}</p>
            <p className="text-xs text-muted-foreground mt-2">
              {variant === 'live' 
                ? t('randomNumbersWillBeDifferent')
                : t('actualIdGeneratedOnServer')
              }
            </p>
          </div>
        ) : (
          <div className="p-4 bg-muted rounded-lg font-mono text-lg text-muted-foreground">
            {variant === 'live' ? t('addElementsToSeePreview') : t('noPreviewAvailable')}
          </div>
        )}
      </CardContent>
    </Card>
  )
}

